services:
  web:
    build:
      context: .
    container_name: springapp
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0110
    ports:
      - "5432:5432"
    container_name: springapp-postgres
